
  const env = {
    REACT_APP_API_KEY: '9f153230ddd091a424667b32459449c3',
    REACT_APP_API_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5ZjE1MzIzMGRkZDA5MWE0MjQ2NjdiMzI0NTk0NDljMyIsInN1YiI6IjY1MTQzZGZkZWE4NGM3MDBjYTA1Yzc3ZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ",
    REACT_APP_API_AUTHENTICATE:"eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5ZjE1MzIzMGRkZDA5MWE0MjQ2NjdiMzI0NTk0NDljMyIsInN1YiI6IjY1MTQzZGZkZWE4NGM3MDBjYTA1Yzc3ZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Q8ds2BIDSgXXCLC5noxKz3XPnOboof24lMvvReMMGGs",
  };

  const getConfig = () => {
    return {
      apiKey: env.REACT_APP_API_KEY,
      requestToken: env.REACT_APP_API_TOKEN,
      authenticate: env.REACT_APP_API_AUTHENTICATE,
    };
  };

  export default getConfig;